#! /bin/bash

/sbin/rmmod cx18;
/sbin/rmmod saa7134;
/sbin/rmmod ov51x_jpeg;
/sbin/modprobe saa7134 car=3 tuner=39;
/sbin/modprobe cx18;
# Disable dynamic power management (screen blanking)
/usr/bin/xset -dpms
# Disable screen saver
/usr/bin/xset s off
#/sbin/modprobe ov51x_jpeg;
service mythbackend start
irsend send_once gray 1
irexec -d /home/mythy/.lircrc
