./files2.sh 300.avi
./files2.sh AI.avi
./files2.sh DVD_VIDEO.mp4
./files2.sh VAMPIRE_AFFECT_SUB_ENG.vob
./files2.sh Haraldandkumarescapefromguantanimobay.mp4
./files2.sh HAROLD_KUMAR_2.vob
./files2.sh Dark-Secret-of-Hendrik-Schon.nuv
./files2.sh Presidential_Inauguration.nuv
./files2.sh Kung.Fu.Panda[2008]DvDrip-aXXo.avi
./files2.sh Transformers
./files2.sh Repo_The_Genetic_Opera_V2.vob
